/**
 * js/event.js
 * ---------------------------------------------------------------------------
 * Event detail page controller.
 *
 * Required behaviour from the assessment brief, and where it happens here:
 *   * "only displays the details for the specific event selected from the Home
 *      or Search pages ... utilise URL query strings or Local Storage to pass
 *      the event id and fetch the correct data via your API"
 *        -> readEventIdFromUrl() reads ?id=7; the last id the visitor opened is
 *           also remembered in localStorage as a fallback, so the page still
 *           works if the query string is lost.
 *   * "display all relevant event details retrieved from your API with a
 *      professional and engaging layout"
 *        -> renderEvent() builds the hero, the facts list, the full
 *           description, the purpose and the organisation panel.
 *   * "ticket information (the price, or even a free one)"
 *        -> renderTickets() lists every ticket tier and marks free tiers.
 *   * "Goal vs. Progress (for a specific charity goal)"
 *        -> dom.js progressBar() draws the goal against the donations total.
 *   * "Include a Register button ... trigger a simple modal or alert dialog
 *      stating 'This feature is currently under construction.'"
 *        -> the button calls modal.js showUnderConstructionModal().
 */
import { getEventById, ApiError } from './api.js';
import { initLayout } from './nav.js';
import {
  el,
  select,
  imageUrl,
  stateBadge,
  progressBar,
  formatDate,
  formatDateRange,
  formatTime,
  formatPrice,
  formatCurrency,
  showError,
} from './dom.js';
import { showUnderConstructionModal } from './modal.js';
import { t, onLanguageChange } from './i18n.js';

const STORAGE_KEY = 'charity-events:last-viewed-event-id';

/* ------------------------------------------------------------------ */
/* Startup                                                             */
/* ------------------------------------------------------------------ */
document.addEventListener('DOMContentLoaded', () => {
  initLayout();

  const eventId = readEventId();

  if (!eventId) {
    renderMissingId();
  } else {
    loadEvent(eventId);
  }

  // The whole detail page is generated by this module, so a language change has
  // to rebuild it from the data that is already in memory rather than re-fetch.
  onLanguageChange(() => {
    if (currentEvent) {
      renderEvent(currentEvent);
    } else {
      renderMissingId();
    }
    appendBackLink(select('#event-root'));
  });
});

/** The event currently on screen, kept so a language change can re-render it. */
let currentEvent = null;

/* ------------------------------------------------------------------ */
/* Reading the event id                                                */
/* ------------------------------------------------------------------ */

/**
 * Get the event id, preferring the query string (the method the brief
 * suggests) and falling back to localStorage.
 */
function readEventId() {
  const fromQuery = new URLSearchParams(window.location.search).get('id');

  if (fromQuery !== null && fromQuery !== '') {
    // Remember it for a later visit without the query string.
    try {
      window.localStorage.setItem(STORAGE_KEY, fromQuery);
    } catch (error) {
      // Private browsing can block localStorage; the query string still works.
    }
    return fromQuery;
  }

  try {
    const stored = window.localStorage.getItem(STORAGE_KEY);
    if (stored) {
      // Put the id back into the address bar so the URL stays shareable.
      window.history.replaceState({}, '', `?id=${encodeURIComponent(stored)}`);
      return stored;
    }
  } catch (error) {
    // ignore
  }

  return null;
}

/* ------------------------------------------------------------------ */
/* Loading and rendering                                               */
/* ------------------------------------------------------------------ */
async function loadEvent(eventId) {
  const root = select('#event-root');

  try {
    const event = await getEventById(eventId);
    renderEvent(event);
  } catch (error) {
    if (error instanceof ApiError && error.status === 404) {
      showError(root, error.message, [t('error.eventSuspendedHint')]);
    } else {
      showError(root, error.friendlyMessage || t('error.eventLoadFailed'), error.details);
    }
    appendBackLink(root);
  }
}

/** Build the complete page for one event. */
function renderEvent(event) {
  const root = select('#event-root');

  currentEvent = event;
  document.title = t('event.detailTitle', { name: event.eventName });
  select('#breadcrumb-event').textContent = event.eventName;

  root.replaceChildren(
    buildHero(event),
    buildDetailSection(event)
  );
}

/* ------------------------------------------------------------------ */
/* Hero                                                                */
/* ------------------------------------------------------------------ */
function buildHero(event) {
  const section = el('section', { className: 'event-hero' });
  const container = el('div', { className: 'container' });
  const grid = el('div', { className: 'event-hero__grid' });

  /* --- left: the headline facts ---------------------------------- */
  const copy = el('div');

  const meta = el('div', { className: 'event-hero__meta' });
  meta.append(stateBadge(event.eventState));
  meta.append(
    el('span', {
      className: 'chip',
      text: event.categoryName || t('state.charityEvent'),
    })
  );
  meta.append(
    el('span', {
      className: 'price',
      text: priceSummary(event),
    })
  );

  const title = el('h1', { text: event.eventName });

  const lead = el('p', { className: 'event-hero__lead', text: event.shortDescription });

  const facts = el('ul', { className: 'fact-list' });
  [
    [t('event.detailDate'), formatDate(event.dateStart)],
    [t('event.detailTime'), `${formatTime(event.startTime)} - ${formatTime(event.endTime)}`],
    [
      t('event.detailVenue'),
      `${event.venueName}${event.address && event.address !== 'N/A' ? `, ${event.address}` : ''}`,
    ],
    [t('event.detailLocation'), `${event.city} ${event.state || ''} ${event.postcode || ''}`.trim()],
    [t('event.detailOrganiser'), event.organizationName],
    [
      t('event.detailCapacity'),
      event.capacity
        ? t('event.capacityPlaces', { count: event.capacity })
        : t('event.capacityUnlimited'),
    ],
  ].forEach(([label, value]) => {
    const item = el('li');
    item.append(
      el('span', { className: 'fact-list__label', text: label }),
      el('span', { className: 'fact-list__value', text: value })
    );
    facts.append(item);
  });

  copy.append(meta, title, lead, facts);

  /* --- right: image ---------------------------------------------- */
  const media = el('div', { className: 'event-hero__media' });
  media.append(
    el('img', {
      attributes: {
        src: imageUrl(event),
        alt: t('a11y.eventIllustration', { name: event.eventName }),
        width: '720',
        height: '450',
      },
    })
  );

  grid.append(copy, media);
  container.append(grid);
  section.append(container);
  return section;
}

/** "Free entry", "From $20.00" or "Tickets from $20.00 to $480.00". */
function priceSummary(event) {
  const prices = (event.ticketTypes || []).map((ticket) => ticket.price);

  if (event.isFree || (prices.length > 0 && prices.every((price) => price === 0))) {
    return t('event.freeEntry');
  }
  if (prices.length === 0) {
    return t('event.contactForPrices');
  }

  const min = Math.min(...prices.filter((price) => price > 0));
  const max = Math.max(...prices);
  if (min === max) return t('event.ticketsSingle', { price: formatPrice(min) });
  return t('event.ticketsFromTo', { min: formatPrice(min), max: formatPrice(max) });
}

/* ------------------------------------------------------------------ */
/* Main content + sidebar                                              */
/* ------------------------------------------------------------------ */
function buildDetailSection(event) {
  const container = el('div', { className: 'container' });
  const grid = el('div', { className: 'detail-grid' });

  grid.append(buildProse(event), buildSideColumn(event));
  container.append(grid);
  return container;
}

/** Full description, purpose and organiser information. */
function buildProse(event) {
  const prose = el('div', { className: 'prose' });

  prose.append(el('h2', { text: t('event.aboutHeading') }));
  // The description is one paragraph per blank line, so a long text stays
  // readable without trusting it as HTML.
  event.description
    .split(/\n+/)
    .filter((paragraph) => paragraph.trim() !== '')
    .forEach((paragraph) => {
      prose.append(el('p', { text: paragraph.trim() }));
    });

  prose.append(el('h2', { text: t('event.purposeHeading') }));
  prose.append(el('p', { text: event.purpose }));

  prose.append(el('h2', { text: t('event.fundsHeading') }));
  const uses = el('ul');
  [t('event.funds1'), t('event.funds2'), t('event.funds3')].forEach((line) =>
    uses.append(el('li', { text: line }))
  );
  prose.append(uses);

  prose.append(el('h2', { text: t('event.accessHeading') }));
  prose.append(el('p', { text: t('event.accessBody') }));

  prose.append(el('h2', { text: t('event.statusHeading') }));
  prose.append(
    el('p', {
      text:
        event.eventState === 'past'
          ? t('event.statusPast', { date: formatDate(event.dateEnd) })
          : event.eventState === 'ongoing'
            ? t('event.statusOngoing')
            : t('event.statusUpcoming', { date: formatDateRange(event) }),
    })
  );

  return prose;
}

/** Registration, tickets and the goal progress bar. */
function buildSideColumn(event) {
  const column = el('div', { className: 'side-column' });

  column.append(
    buildGoalPanel(event),
    buildTicketPanel(event),
    buildOrganiserPanel(event)
  );

  return column;
}

/** Goal vs progress - the fundraising goal against the donations recorded. */
function buildGoalPanel(event) {
  const panel = el('div', { className: 'panel panel--brand' });
  panel.append(el('h2', { text: t('event.goalHeading') }));
  panel.append(el('p', { text: t('event.goalLead', { organisation: event.organizationName }) }));
  panel.append(progressBar(event));

  const summary = el('ul', { className: 'contact-list' });
  [
    [t('event.goalRow'), formatCurrency(event.goalAmount)],
    [t('event.raisedRow'), formatCurrency(event.raisedAmount)],
    [t('event.remainingRow'), formatCurrency(Math.max(event.goalAmount - event.raisedAmount, 0))],
    [t('event.donationsRow'), t('event.donationsValue', { count: event.donationCount || 0 })],
  ].forEach(([label, value]) => {
    const item = el('li');
    item.append(el('span', { text: label }), el('span', { text: value }));
    summary.append(item);
  });
  panel.append(summary);

  return panel;
}

/** Ticket tiers, the Register button and the (A3) registration form. */
function buildTicketPanel(event) {
  const panel = el('div', { className: 'panel panel--accent' });
  panel.append(el('h2', { text: t('event.ticketsHeading') }));

  const tickets = event.ticketTypes || [];

  if (tickets.length === 0) {
    panel.append(el('p', { text: t('event.ticketsMissing') }));
  } else {
    const list = el('ul', { className: 'ticket-list' });
    tickets.forEach((ticket) => {
      const item = el('li', {
        className: ticket.price === 0 ? 'ticket ticket--free' : 'ticket',
      });

      const name = el('span', { className: 'ticket__name', text: ticket.ticketName });
      if (ticket.description) {
        name.append(el('span', { className: 'ticket__desc', text: ticket.description }));
      }
      if (ticket.quantityAvailable !== null && ticket.quantityAvailable !== undefined) {
        name.append(
          el('span', {
            className: 'ticket__availability',
            text:
              ticket.quantityAvailable > 0
                ? t('event.availableCount', { count: ticket.quantityAvailable })
                : t('event.soldOut'),
          })
        );
      }

      item.append(
        name,
        el('span', {
          className: 'ticket__price',
          text: ticket.price === 0 ? t('event.free') : formatPrice(ticket.price),
        })
      );
      list.append(item);
    });
    panel.append(list);
  }

  const registerButton = el('button', {
    className: 'button button--block',
    text: event.eventState === 'past' ? t('event.registerClosed') : t('event.register'),
    attributes: {
      type: 'button',
      id: 'register-button',
      'aria-haspopup': 'dialog',
    },
  });
  registerButton.addEventListener('click', () => {
    // The exact message required by the brief is produced inside modal.js.
    showUnderConstructionModal(t('modal.registerFeature', { name: event.eventName }));
  });
  panel.append(registerButton);

  panel.append(buildRegistrationForm(event));

  panel.append(
    el('p', { className: 'register-note', text: t('event.registerNote') })
  );

  return panel;
}

/**
 * A registration form that demonstrates the layout AND the client-side
 * validation pattern. It deliberately does not send anything yet, because
 * Assessment 2 only requires GET endpoints.
 */
function buildRegistrationForm(event) {
  const wrapper = el('div', { className: 'registration-form' });
  wrapper.append(el('h3', { text: t('event.registerFormHeading') }));

  const form = el('form', { attributes: { id: 'registration-form', novalidate: 'novalidate' } });

  const row = el('div', { className: 'form-row' });

  const nameField = el('div', { className: 'field' });
  nameField.append(
    el('label', { text: t('event.fullName'), attributes: { for: 'reg-name' } }),
    el('input', {
      attributes: { type: 'text', id: 'reg-name', name: 'fullName', autocomplete: 'name' },
    })
  );

  const emailField = el('div', { className: 'field' });
  emailField.append(
    el('label', { text: t('event.email'), attributes: { for: 'reg-email' } }),
    el('input', {
      attributes: { type: 'email', id: 'reg-email', name: 'email', autocomplete: 'email' },
    })
  );

  row.append(nameField, emailField);

  const ticketField = el('div', { className: 'field' });
  ticketField.append(
    el('label', { text: t('event.preferredTicket'), attributes: { for: 'reg-ticket' } })
  );
  const ticketSelect = el('select', { attributes: { id: 'reg-ticket', name: 'ticketTypeId' } });
  (event.ticketTypes || []).forEach((ticket) => {
    ticketSelect.append(
      el('option', {
        text: `${ticket.ticketName} - ${
          ticket.price === 0 ? t('event.free') : formatPrice(ticket.price)
        }`,
        attributes: { value: String(ticket.ticketTypeId) },
      })
    );
  });
  if ((event.ticketTypes || []).length === 0) {
    ticketSelect.append(
      el('option', { text: t('event.ticketTba'), attributes: { value: '' } })
    );
  }
  ticketField.append(ticketSelect);

  const quantityField = el('div', { className: 'field' });
  quantityField.append(
    el('label', { text: t('event.quantity'), attributes: { for: 'reg-quantity' } }),
    el('input', {
      attributes: { type: 'number', id: 'reg-quantity', name: 'quantity', min: '1', max: '10', value: '1' },
    })
  );

  const message = el('p', {
    className: 'field-message',
    attributes: { id: 'reg-message', role: 'status', 'aria-live': 'polite' },
  });

  const submit = el('button', {
    className: 'button button--secondary button--block',
    text: t('event.submitRegistration'),
    attributes: { type: 'submit' },
  });

  form.append(row, ticketField, quantityField, submit, message);

  // Client-side validation, then the same "under construction" dialog that the
  // Register button shows.
  form.addEventListener('submit', (domEvent) => {
    domEvent.preventDefault();

    const name = form.querySelector('#reg-name').value.trim();
    const email = form.querySelector('#reg-email').value.trim();
    const quantity = Number(form.querySelector('#reg-quantity').value);

    if (name.length < 2) {
      message.textContent = t('event.validationName');
      message.className = 'field-message field-message--error';
      form.querySelector('#reg-name').focus();
      return;
    }
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      message.textContent = t('event.validationEmail');
      message.className = 'field-message field-message--error';
      form.querySelector('#reg-email').focus();
      return;
    }
    if (!Number.isInteger(quantity) || quantity < 1 || quantity > 10) {
      message.textContent = t('event.validationQuantity');
      message.className = 'field-message field-message--error';
      form.querySelector('#reg-quantity').focus();
      return;
    }

    message.textContent = t('event.validationSuccess', { name });
    message.className = 'field-message field-message--success';

    showUnderConstructionModal(t('modal.submitFeature'));
  });

  wrapper.append(form);
  return wrapper;
}

/** Contact panel for the organisation running the event. */
function buildOrganiserPanel(event) {
  const panel = el('div', { className: 'panel' });
  panel.append(el('h2', { text: t('event.organisedBy') }));
  panel.append(el('h3', { text: event.organizationName }));
  panel.append(el('p', { text: t('event.organiserBody') }));
  const list = el('ul', { className: 'contact-list' });
  const city = el('li');
  city.append(el('span', { text: t('event.basedIn') }), el('span', { text: event.city }));
  list.append(city);
  panel.append(list);
  panel.append(
    el('p', {
      text: t('event.moreEvents'),
      attributes: { href: 'search.html', class: 'button button--small button--outline' },
    })
  );
  return panel;
}

/* ------------------------------------------------------------------ */
/* Fallbacks                                                           */
/* ------------------------------------------------------------------ */

/** Shown when no id is present in the URL or in localStorage. */
function renderMissingId() {
  const root = select('#event-root');
  showError(root, t('event.noIdTitle'), [t('event.noIdHint')]);
  appendBackLink(root);
}

/** A safe way back if something went wrong. */
function appendBackLink(root) {
  const container = root.querySelector('.container') || root;
  const paragraph = el('p');
  paragraph.style.textAlign = 'center';
  paragraph.append(
    el('a', {
      className: 'button button--outline',
      text: t('error.backHome'),
      attributes: { href: 'index.html' },
    }),
    el('a', {
      className: 'button button--ghost',
      text: t('error.searchForEvent'),
      attributes: { href: 'search.html' },
    })
  );
  container.append(paragraph);
}
